SRC_DIR = src
DATA_DIR = data
FUNCT = sphere
MAX_ITERS = 10000
SIZE = 100
CROSS = 0.9
SCALE = 0.7
DIM = 10

run:
	@python3 ./$(SRC_DIR)/main.py -f $(FUNCT) -m $(MAX_ITERS) -s $(SIZE) -cr $(CROSS) -sc $(SCALE) -d $(DIM)
