functions:
  using: 'ackley'
  sphere:
    bound: 5.12
  ackley:
    bound: 30
  griewank:
    bound: 600
  tenth:
    bound: 5.12
  rastrigin:
    bound: 5.12
  rosenbrock:
    bound: 2.048

maxevals: 1000
size: 10
dim: 2
omega: 0.7
phip: 0.5
phig: 0.5
lr: 0.4
