functions:
  using: 'c'
  cosin:
    blo: -1.5
    bup: 5
  a:
    blo: 0
    bup: 5
  b:
    blo: 0
    bup: 20
  c:
    blo: 1
    bup: 5

maxevals: 50
size: 200
dim: 2
omega: 0.6
phip: 0.8
phig: 0.3
lr: 0.2
nBest: 3
