functions:
  using: 'sphere'
  sphere:
    blo: -5.12
    bup: 5.12
  cosin:
    blo: -1.5
    bup: 5
  a:
    blo: 0
    bup: 5
  b:
    blo: 0
    bup: 20
  c:
    blo: 1
    bup: 5

maxevals: 30
size: 50
dim: 2
omega: 0.75
phip: 0.3
phig: 0.7
lr: 0.4
nBest: 3
